# Generated by Django 5.2.4 on 2025-09-02 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('transaction_type', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], max_length=10, verbose_name='ประเภท')),
                ('category', models.CharField(choices=[('salary', 'เงินเดือน'), ('bonus', 'โบนัส'), ('investment', 'เงินลงทุน'), ('other_income', 'รายรับอื่นๆ'), ('food', 'อาหาร'), ('transport', 'คมนาคม'), ('entertainment', 'บันเทิง'), ('shopping', 'ช้อปปิ้ง'), ('bills', 'ค่าบิล'), ('health', 'สุขภาพ'), ('education', 'การศึกษา'), ('other_expense', 'รายจ่ายอื่นๆ')], max_length=20, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'รายการธุรกรรม',
                'verbose_name_plural': 'รายการธุรกรรม',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
