# Generated by Django 5.2.4 on 2026-01-29 12:38

import django.db.models.deletion
from django.db import migrations, models


def clear_old_transaction_category(apps, schema_editor):
    """
    ลบข้อมูล Transaction เก่าที่ใช้ค่า category เป็นตัวอักษร
    เพื่อหลีกเลี่ยง IntegrityError ตอนเปลี่ยน field เป็น ForeignKey
    (โปรเจ็กต์นี้เป็นงานเรียน/ทดสอบ จึงยอมลบข้อมูลเก่าได้)
    """
    Transaction = apps.get_model('ICANDEP', 'Transaction')
    Transaction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ICANDEP', '0003_alter_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('transaction_type', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], max_length=10, verbose_name='ประเภท')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='ไอคอน')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ['transaction_type', 'name'],
                'unique_together': {('name', 'transaction_type')},
            },
        ),
        # เคลียร์ค่าหมวดหมู่เก่าที่เป็นตัวอักษรทิ้ง ก่อนจะเปลี่ยน field เป็น ForeignKey
        migrations.RunPython(clear_old_transaction_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ICANDEP.category', verbose_name='หมวดหมู่'),
        ),
    ]
